task :build_plugin_env do
  result = system("jar -xf redmine-2.0.3.zip")
  p "Could not execute jar -xf redmine-2.0.3.zip - status = " + $?.to_s if result.nil? or not result
end

task :default => ["build_plugin_env"]